name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/build_system_fixed_tests # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and run container
        run: |
          docker build -t bertoslav .
          